# mapping
## zh & punctuation
## training_params: old_areas_list, seed 
mapping:
  old_areas_list:
  - [0x4E00, 0x9FFF]  # Unicode zh
  - 0x3002
  - 0xFF1F
  - 0xFF01
  - 0x3010
  - 0x3011
  - 0xFF0C
  - 0x3001
  - 0xFF1B
  - 0xFF1A
  - 0x300C
  - 0x300D
  - 0x300E
  - 0x300F
  - 0x2019
  - 0x201C
  - 0x201D
  - 0x2018
  - 0xFF08
  - 0xFF09
  - 0x3014
  - 0x3015
  - 0x2026
  - 0x2013
  - 0xFF0E
  - 0x2014
  - 0x300A
  - 0x300B
  - 0x3008
  - 0x3009
  seed: 42
  mapping_file: null # if not exist, will be trained and saved here

## tokenizer
## training_params: path
new_lang_tokenizer:
  type: default
  path: mix/new_tokenizer

## mix training
model_name_or_path: /home/nfs06/shenyz/models/Qwen2.5-0.5B
mix_trained:
  doc_path: null
  counter_path: [data/en.bin, data/zh.bin]
  level: 2
  seed: 42
  expand: 0
  expand_only: false

output_dir: mix/
